Repository la-niche/nonos, pull requests merged in 2024-04, with the labels that each got.

#292 BUG: fix a regression in GasField.map (revert #189)
  nonos/api/analysis.py
  tests/test_plotting.py
Labels: bug

#296 BUG: fix a broken fstring
  nonos/_readers/binary.py
Labels: bug

#310 DOC: cleanup out-of-sync badge
  README.md
Labels: documentation

#303 ENH: NonosLick with new lick options
  nonos/api/satellite.py
  pyproject.toml
  tests/pytest_mpl_baseline/test_nonoslick_method_linear.png
  tests/pytest_mpl_baseline/test_nonoslick_method_nearest.png
  tests/test_image_comp.py
Labels: enhancement

#329 ENH: return path to saved file in GasField.save
  nonos/api/analysis.py
  tests/test_load_data.py
Labels: enhancement

#330 TST: fix 3 bugs in `NPYReader` related to reading from directories which lack density files
  nonos/_readers/binary.py
  tests/test_interfaces/test_binary_readers.py
Labels: bug
